# Numpy for dummies !

## List vs Arrays 

In [1]:
import numpy as np
L = [1,2,3]
A = np.array([1,2,3])

A.append(4) #doesn't work with np array
A = A + [4, 5] #doesn't work with np array


AttributeError: 'numpy.ndarray' object has no attribute 'append'

The + sign in numpy does vector addition, it does not concatenate like a regular array

In [2]:
A + A

array([2, 4, 6])

### Numpy methods

In [3]:
np.sqrt(A) #square root

array([1.        , 1.41421356, 1.73205081])

In [5]:
np.log(A) # logarithm

array([0.        , 0.69314718, 1.09861229])

In [6]:
np.exp(A) #exponential

array([ 2.71828183,  7.3890561 , 20.08553692])

## Dot Product
### For loop vs. cosine method vs. dot function

In [7]:
a = np.array([1,2])
b = np.array([2,1])
dot =0 
for e, f in zip(a,b):
    dot +=e*f
dot

4

In [8]:
np.sum(a*b)

4

The sum function is an instant method of the numpy array

In [9]:
(a*b).sum()

4

More convenient way:

In [10]:
np.dot(a,b)

4

### Vectors and Matrices

In [13]:
M = np.array([[1,2], [3,4]])
L = [[1,2], [3,4]]

How to access values in numpy arrays ?

In [14]:
M[0,0]

1

Transpose an array with array.T

In [16]:
M.T

array([[1, 3],
       [2, 4]])

### Generating Matrices to work with

In [17]:
np.array([1,2,3]) #not convenient

array([1, 2, 3])

Create an array of zeros with np.zeros(numberOfZeros)

In [27]:
Z = np.zeros(10) 
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
Z = np.zeros((10,10))
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Create an array of 1 with np.ones()

In [31]:
O = np.ones((10,10))
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Create a random (numbers between 0,1) array with np.random.random()

In [34]:
R = np.random.random((5,5))
R

array([[0.12832018, 0.07799104, 0.38325177, 0.4782232 , 0.60505806],
       [0.61678858, 0.4725594 , 0.56447706, 0.56307836, 0.09485785],
       [0.55191242, 0.67596767, 0.97604593, 0.69638127, 0.56311779],
       [0.87638758, 0.73773596, 0.13758959, 0.73900445, 0.12611148],
       [0.19747016, 0.73510656, 0.94709873, 0.72350625, 0.58718313]])

Create a random array (gaussian distribution) with np.random.randn()

In [35]:
G = np.random.randn(5,5) #carefull! no tupple in arguments
G

array([[-1.64889955,  0.45423808,  0.01060602, -1.43371119,  3.06830367],
       [ 1.15712325,  0.4413644 ,  0.28795593,  0.57183156,  0.6416097 ],
       [-1.20891817, -0.73186709, -0.15048594,  0.67502835, -0.51972439],
       [ 0.39797103, -1.34659757, -0.25824376, -0.18357303, -0.13267509],
       [-0.7175188 ,  1.09224457, -0.03218942, -0.24326068, -1.94398642]])

Find the mean

In [36]:
G.mean()

-0.07013498082681559

Find the variance

In [37]:
G.var()

1.0804010326966262